development:
#  adapter: async
  adapter: redis
  url: redis://localhost:6379

test:
  adapter: test

production:
  adapter: <%= ENV['CABLE_ADAPTER'] || 'postgresql' %>
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: greenlight_production